version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: travel_db
    restart: always
    environment:
      MYSQL_DATABASE: travel_db
      MYSQL_USER: tfg_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
