version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mi_bd
      POSTGRES_USER: mi_usuario
      POSTGRES_PASSWORD: mi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./server
    environment:
      DB_NAME: mi_bd
      DB_USER: mi_usuario
      DB_PASSWORD: mi_password
      DB_HOST: db
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  postgres_data:
